# Generated by Django 5.1.15 on 2026-08-28 01:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "event_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("audit_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("request_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("event_type", models.CharField(db_index=True, max_length=64)),
                ("schema_version", models.CharField(default="audit-v1", max_length=16)),
                ("farm_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("principal_user_id", models.UUIDField(db_index=True)),
                ("conversation_id", models.UUIDField(blank=True, null=True)),
                ("message_id", models.UUIDField(blank=True, null=True)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["audit_id", "created_at"],
                        name="assistant_a_audit_i_d24e5a_idx",
                    ),
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="assistant_a_event_t_025cab_idx",
                    ),
                ],
            },
        ),
    ]
