# Generated by Django 5.1.15 on 2026-08-28 01:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CorpusSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("snapshot_id", models.CharField(max_length=64, unique=True)),
                ("index_key", models.CharField(default="gov_tier_a", max_length=32)),
                ("is_active", models.BooleanField(default=False)),
                ("manifest_checksum", models.CharField(max_length=64)),
                ("chunk_count", models.PositiveIntegerField(default=0)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "chunk_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("parent_id", models.UUIDField(blank=True, null=True)),
                ("document_id", models.UUIDField(blank=True, null=True)),
                ("farm_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("index_key", models.CharField(db_index=True, max_length=32)),
                (
                    "snapshot_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("tier", models.CharField(blank=True, max_length=1, null=True)),
                ("doc_title", models.TextField()),
                ("source_url", models.TextField(blank=True, null=True)),
                ("heading_path", models.JSONField(blank=True, default=list)),
                ("section_path", models.TextField(blank=True, default="")),
                ("chunk_index", models.IntegerField()),
                ("token_count", models.IntegerField()),
                ("content_hash", models.CharField(max_length=64)),
                ("text", models.TextField()),
                (
                    "doc_state",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("superseded_by", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["snapshot_id", "chunk_index"],
                "indexes": [
                    models.Index(
                        fields=["farm_id", "index_key", "doc_state"],
                        name="documents_d_farm_id_741413_idx",
                    ),
                    models.Index(
                        fields=["snapshot_id"], name="documents_d_snapsho_e949c6_idx"
                    ),
                    models.Index(
                        fields=["content_hash"], name="documents_d_content_3bc874_idx"
                    ),
                ],
            },
        ),
    ]
